### ISSUE TITLE
Update 1.5 is not more online?

### ISSUE THREAD

**Issue by Titoo8899** [TheHamester/HitIndicator#22]
Hi,
I have see a new Update of your mod was online for 6 hours but it is no data to see. Give it a Problem with this version and
then yes. Then comes the fix of this Problem out?

**Comment by TheHamester** [comment]
we decided to hold it for now

**Comment by TheHamester** [comment]
We just decided to hold the update for some time, cause there are some features from that version that might not stay

**Comment by TheHamester** [comment]
Hello, due to the fact that I burnt myself out, I will be taking a break from working on this mod for an undetermined amount of time, you can use the version provided in the #19, it might not work everywhere, but I just need to take a mental health break from working on hit indication. sorry for the inconvinience.

**Comment by Titoo8899** [comment]
okay can I the 1.12.2 version of this mod I play normal not higher

**Comment by TheHamester** [comment]
[hitindication 1.12.2-1.5.zip](https://github.com/user-attachments/files/16116647/hitindication.1.12.2-1.5.zip)

**Comment by Titoo8899** [comment]
thanks
