### ISSUE TITLE
TinyInv Incompatibility

### ISSUE THREAD

**Issue by SheReyy** [TheHamester/HitIndicator#23]
MC version: 1.20.1
Forge: 47.3.0
Hit Indication: hitindication-1.20.1-1.5.jar [this](https://github.com/TheHamester/HitIndicator/issues/19#issuecomment-2211619731) one
TinyInv: tinyinv-1.20.1-1.1.0.1.jar

Hit Indication won't work when it's installed along side with [TinyInv](https://www.curseforge.com/minecraft/mc-mods/tinyinv). [Here](https://gist.github.com/SheReyy/30deae8cb55f46ea04a3979ae13e2ebe)'s my latest log. Let's hope this is the last incompatible mod

**Comment by TheHamester** [comment]
Hello, due to the fact that I burnt myself out, I will be taking a break from working on this mod for an undetermined amount of time, you can use the version provided in the #19, it might not work everywhere, but I just need to take a mental health break from working on hit indication. sorry for the inconvinience.

**Comment by SheReyy** [comment]
No worries
